### ISSUE TITLE
JsonbArray returns malformed result

### ISSUE THREAD

**Issue by delirehberi** [martin-georgiev/postgresql-for-doctrine#68] opened 2020-05-15 14:21 UTC
I have a field that has `jsonb[]` type. I want to add multidimensional array data to that field. But PostgreSQL returns an error. I tried to find what is wrong but i couldn't succeed.

You can reproduce with that data:
```
[
  [ 
    'id'=>5,
    'text'=>'test'
  ]
]
```
error: 

```
  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  malformed array literal: "{{"id":5,"test":"test"}}" 
DETAIL:  Unexpected array element.
```

There is a start point for finding what is wrong: https://dba.stackexchange.com/questions/54283/how-to-turn-json-array-into-postgres-array/54289#54289

**Comment by martin-georgiev** [comment] 2021-01-23 23:54
Oh, 🐟 !

[The package employs `json_encode` and `json_decode`](https://github.com/martin-georgiev/postgresql-for-doctrine/blob/f03234799d7ebce99d0b06d7ee742446940a61d3/src/MartinGeorgiev/Doctrine/DBAL/Types/JsonTransformer.php#L25) for the transformations and that seems not to be good enough for Postgres.

Can you please confirm when it happens and share complete code for reproducing it?

**Comment by delirehberi** [comment] 2021-01-25 15:19
Hey @martin-georgiev , actually i can't remember when i got that error. But i'll try to reproduce and share complete code with you as soon as possible.

**Comment by martin-georgiev** [comment] 2022-12-05 01:01
Closing due to no further reports of this breaking in later versions. Please reopen if you see it happening again.

**Closed by martin-georgiev** 2022-12-05 01:01 UTC
