### ISSUE TITLE
Wanted to add your package in PHP 8.0.12 project, but PHP version requirement is not met

### ISSUE THREAD

**Issue by TaamKaGG** [martin-georgiev/postgresql-for-doctrine#97] opened 2021-11-05 16:56 UTC
I wanted to use your package in a project using PHP version 8.0.12.

Your package needs at least PHP 7.2 so I thought it would work, but composer stops the process and give me this :

Problem 1
    - martin-georgiev/postgresql-for-doctrine v1.5.0 requires php ^7.2 -> your php version (8.0.12) does not satisfy that requirement.
    - martin-georgiev/postgresql-for-doctrine[v1.5.1, ..., v1.5.2] require doctrine/dbal ~2.5 -> found doctrine/dbal[v2.5.0, ..., 2.13.4] but the package is fixed to 3.1.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires martin-georgiev/postgresql-for-doctrine ^1.5 -> satisfiable by martin-georgiev/postgresql-for-doctrine[v1.5.0, v1.5.1, v1.5.2].

Do you know why does the PHP requirements are not me ?

Thanks for letting me know, and fix bug if it is one

**Comment by jraller** [comment] 2021-11-13 16:29
It looks like the issue is the ~2.5 requirement for dbal. From the message you are in the same situation I'm in where your dbal is beyond 3.0 and so does not match the ~2.5 requirement for dbal which would allow >=2.5.0 < 3.0.0

**Comment by jraller** [comment] 2021-11-13 16:49
After browsing the DBAL upgrade guide and searching for uses of dbal in this codebase no apparent incompatibilities stand out. The use of dbal in this codebase seems to be for DBAL\Types\Type which lists no breaking changes between 2.13 and 3.*

running `composer require -W martin-georgiev/postgres-for-doctrine` did allow the install to go through, but downgraded my dbal from 3.13 to 2.13.5

**Comment by TaamKaGG** [comment] 2021-11-13 18:32
Well, for now, the project I'm working on will probably stay with MariaDB for a few weeks/months, but I'll keep in mind your composer command, as it might be needed in the future (we will go on a PostgreSQL database at some point). 

Thanks a lot for your answer, and I'll keep you updated if I find anything else

**Comment by martin-georgiev** [comment] 2021-11-14 08:56
This shall be fixed once #98 gets merged & released later this week.

**Closed** 2021-11-14 09:01 UTC
